# Workflow that will tell us whether our tests passed or not
name: Test Project
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      # Download the repo with the code
      - name: Checkout
        uses: actions/checkout@v3
        # with:
        #   path: ''

      - name: Install deps
        run: npm ci

      - name: Test react project
        run: npm test
